main: fr.SPFF.TaupeGun.plugin.TaupeGunPlugin
name: TaupeGunPlugin
version: 0.0.1
authors: [Aless#6161, Marco#1398]
comands:
  taupegun:
    description: "Command to use plugin TaupeGunPlugin"
  coucoucc
