main: fr.aless.TaupeGun.plugin.TaupeGunPlugin
name: TaupeGunPlugin
version: 1.3.2
api-version: "1.15"
authors: ['Aless#6161']
load: POSTWORLD
softdepend:
  - MultiWorld
  - MultiverseCore
commands:
  taupegun:
    aliases: [tg]
    description: "Command to use plugin TaupeGunPlugin"
  t:
    description: "Command for a taupe to speak to others of her taupes' team"
  claim:
    description: "Command for a taupe to give her a stuff"
  reveal:
    description: "Command for a taupe to reveal another taupe"
